name 'straps'
maintainer 'Johnathon Schultz'
maintainer_email 'johnathon.schultz@gmail.com'
license 'all_rights'
description 'Bootstraps a dev server for me.'
long_description 'Bootstraps a dev server for me. Bash, dotstash, python, vim, git, etc.'
version '0.1.0'
